### ISSUE TITLE
UpsertConfig metadataTTL property crashing after creation

### ISSUE THREAD

**Issue by jleber** [azaurus1/go-pinot-api#191]
Hey @azaurus1, I hope you're doing well!

First, I want to thank you and congratulate you on the fantastic job with the Terraform Pinot integration.

I noticed that when we use the RealTime Table with the upsert configuration, the provider can create the resource successfully; however, it crashes when trying to read it, such as during subsequent Terraform plans after the initial creation with `terraform apply`. Here’s an example:

```bash
│ Error: Failed to get table
│ 
│   with module.metering-pinot-table["pipesign"].pinot_table.metering,
│   on ../../modules/pinot/table/main.tf line 1, in resource "pinot_table" "metering":
│    1: resource "pinot_table" "metering" {
│ 
│ client: could not unmarshal response JSON: json: cannot unmarshal number
│ 0.0 into Go struct field UpsertConfig.REALTIME.upsertConfig.metadataTTL of
│ type int64
```

Please note that we are using the Startree Pinot service, though I'm not sure if that makes any difference.

In these two pull requests ([PR 1](https://github.com/azaurus1/go-pinot-api/pull/190), [PR 2](https://github.com/azaurus1/terraform-provider-pinot/pull/119)) I proposed changing the data type to `float64`, similar to the `DeletedKeysTTL` property, which appears to be in the same situation but is already set as `float64`.

WDYT? Is it worth making this change?

**Comment by azaurus1** [comment]
Hi @jleber, this looks goo to me, I appreciate the effort you've made for this, I will:
1. merge the go-pinot-api PR
2. release a new version
3. update the terraform provider PR to use the release
4. merge that pr and release a new provider version, which will push it to the terraform registry

I will let you know on this issue when this is all done.

obrigado

**Comment by azaurus1** [comment]
These changes are included in:
- go-pinot-api -> `v0.6.5`
- terraform-provider-pinot -> `v0.7.9`


@jleber, you should be able to pull `v0.7.9` from the terraform registry shortly
